"""
Case Study Generator
Produces a structured, post-ready Markdown case study from pipeline outputs.

Template sections:
  1. Event Overview
  2. Asset Processing Summary (counts, quality stats)
  3. Selection Logic (per-platform with reasons)
  4. Platform Outputs Generated
  5. Quality Assurance (low-confidence flags)
  6. Key Visuals (top 3 assets with scores)
  7. Technical Notes

All data comes from SelectionResult / AssetMetadata — no external calls needed.
"""

from datetime import datetime
from pathlib import Path
from typing import List, Dict
from content_engine.data_types import AssetMetadata, SelectionResult


def _pct(value: float) -> str:
    return f"{value * 100:.0f}%"


def _top_concepts(assets: List[AssetMetadata], n: int = 5) -> List[str]:
    freq: Dict[str, int] = {}
    for a in assets:
        for c in a.scene_concepts[:3]:
            freq[c] = freq.get(c, 0) + 1
    return [c for c, _ in sorted(freq.items(), key=lambda x: x[1], reverse=True)[:n]]


def generate_case_study(
    selections: List[SelectionResult],
    event_name: str,
    event_date: str = "",
    total_assets_processed: int = 0,
) -> str:
    """
    Generate a complete Markdown case study.

    Args:
        selections:               Output of ContentEngine.select_assets()
        event_name:               Display name of the event
        event_date:               Optional date string (defaults to today)
        total_assets_processed:   Total assets fed into the pipeline (for stats)

    Returns:
        Markdown string ready to write to a .md file.
    """
    if not event_date:
        event_date = datetime.now().strftime("%B %d, %Y")

    run_date = datetime.now().strftime("%B %d, %Y at %H:%M")

    # ── Aggregate stats ───────────────────────────────────────────────────────
    all_assets = [s.asset for s in selections]
    images     = [a for a in all_assets if a.asset_type == "image"]
    videos     = [a for a in all_assets if a.asset_type == "video"]

    collage_sel    = [s for s in selections if s.intended_use == "collage"]
    reel_sel       = [s for s in selections if s.intended_use == "reel"]
    story_sel      = [s for s in selections if s.intended_use == "story"]
    case_study_sel = [s for s in selections if s.intended_use == "case_study"]
    low_conf       = [s for s in selections if s.low_confidence]

    avg_quality   = (sum(a.quality_score   for a in all_assets) / len(all_assets)) if all_assets else 0
    avg_aesthetic = (sum(a.aesthetic_score for a in all_assets) / len(all_assets)) if all_assets else 0
    total_faces   = sum(a.face_count for a in all_assets)
    top_concepts  = _top_concepts(all_assets)

    total_processed = total_assets_processed or len(selections)

    # ── Build document ────────────────────────────────────────────────────────
    lines = []

    # Header
    lines += [
        f"# Case Study: {event_name}",
        "",
        f"> Auto-generated by Content & Design Engine · {run_date}",
        "",
        "---",
        "",
    ]

    # 1. Event Overview
    lines += [
        "## 1. Event Overview",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Event Name | {event_name} |",
        f"| Event Date | {event_date} |",
        f"| Report Generated | {run_date} |",
        f"| Total Assets Processed | {total_processed} |",
        f"| Assets Selected | {len(selections)} |",
        "",
    ]

    # 2. Asset Processing Summary
    lines += [
        "## 2. Asset Processing Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Images selected | {len(images)} |",
        f"| Videos selected | {len(videos)} |",
        f"| Average quality score | {_pct(avg_quality)} |",
        f"| Average aesthetic score | {_pct(avg_aesthetic)} |",
        f"| Total faces detected | {total_faces} |",
        f"| Low-confidence flags | {len(low_conf)} |",
        "",
    ]

    if top_concepts:
        lines += [
            "**Most detected scene concepts:**",
            "",
        ]
        for c in top_concepts:
            lines.append(f"- {c}")
        lines.append("")

    # 3. Selection Logic
    lines += [
        "## 3. Selection Logic",
        "",
        "Each asset was scored on four axes: technical quality, aesthetic quality, "
        "face presence, and event-concept relevance. The composite score determines "
        "platform assignment.",
        "",
        "| Weight | Axis |",
        "|--------|------|",
        "| 30% | Technical quality (sharpness + exposure) |",
        "| 20% | Aesthetic quality (CLIP similarity) |",
        "| 30% | Face presence (engagement signal) |",
        "| 20% | Concept relevance (Florence-2 detection) |",
        "",
    ]

    # Per-platform selection table
    platform_map = {
        "collage":    ("LinkedIn Collage",    collage_sel),
        "reel":       ("Instagram Reel",      reel_sel),
        "story":      ("Instagram Stories",   story_sel),
        "case_study": ("Case Study Visuals",  case_study_sel),
    }

    for platform_key, (platform_label, sels) in platform_map.items():
        if not sels:
            continue
        lines += [
            f"### {platform_label}",
            "",
            f"| Asset | Confidence | Faces | Quality | Reason |",
            f"|-------|-----------|-------|---------|--------|",
        ]
        for s in sels:
            name = Path(s.asset.path).name
            lines.append(
                f"| `{name}` | {_pct(s.confidence)} | {s.asset.face_count} "
                f"| {_pct(s.asset.quality_score)} | {s.selection_reason} |"
            )
        lines.append("")

    # 4. Platform Outputs
    lines += [
        "## 4. Platform Outputs Generated",
        "",
        "| Platform | Format | Count |",
        "|----------|--------|-------|",
        f"| LinkedIn | 1080×1080 collage JPEG | 1 |",
        f"| Instagram Carousel | 1080×1350 JPEG per slide | {len(collage_sel)} slides |",
        f"| Instagram Reel | 1080×1920 MP4 | {'1 video' if reel_sel else 'N/A (no video)'} |",
        f"| Instagram Stories | 1080×1920 JPEG per frame | {len(story_sel)} frames |",
        "",
    ]

    # 5. Quality Assurance
    lines += [
        "## 5. Quality Assurance",
        "",
    ]

    if low_conf:
        lines += [
            f"⚠️ **{len(low_conf)} asset(s) flagged for manual review** "
            f"(confidence < 50%):",
            "",
        ]
        for s in low_conf:
            lines.append(
                f"- `{Path(s.asset.path).name}` — "
                f"confidence {_pct(s.confidence)}, "
                f"intended use: {s.intended_use}"
            )
        lines.append("")
    else:
        lines += [
            "✅ All selected assets passed the confidence threshold (≥ 50%).",
            "",
        ]

    overall = "Recommended for publication" if avg_quality >= 0.6 else \
              "Review recommended before publishing"
    lines += [
        f"**Overall assessment:** {overall} "
        f"(average quality {_pct(avg_quality)})",
        "",
    ]

    # 6. Key Visuals
    top3 = sorted(all_assets, key=lambda a: a.final_score, reverse=True)[:3]
    if top3:
        lines += [
            "## 6. Key Visuals",
            "",
            "Top 3 assets by composite score:",
            "",
            "| Rank | Asset | Score | Quality | Aesthetic | Faces | Concepts |",
            "|------|-------|-------|---------|-----------|-------|----------|",
        ]
        for i, a in enumerate(top3, 1):
            concepts_str = ", ".join(a.scene_concepts[:3]) or "—"
            lines.append(
                f"| {i} | `{Path(a.path).name}` | {_pct(a.final_score)} "
                f"| {_pct(a.quality_score)} | {_pct(a.aesthetic_score)} "
                f"| {a.face_count} | {concepts_str} |"
            )
        lines.append("")

    # 7. Technical Notes
    lines += [
        "## 7. Technical Notes",
        "",
        "| Component | Model / Method |",
        "|-----------|----------------|",
        "| Quality assessment | Laplacian blur + HSV brightness + CLIP aesthetic |",
        "| Face detection | YOLOv11-nano (AdamCodd/YOLOv11n-face-detection) |",
        "| Content understanding | Microsoft Florence-2-base (object detection) |",
        "| Video highlights | PySceneDetect + CLIP frame scoring + librosa audio energy |",
        "| Layout assembly | Pillow smart-crop (face-anchored) + ffmpeg reel assembly |",
        "",
        "_This document was automatically generated. No manual curation was applied._",
    ]

    return "\n".join(lines)
